# Site
name: "MotetHansen"
description: "Keep on learning..."
meta_description: "Keep on learning..."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
google_analytics: 'UA-55230139-1'
disqus: 'motethansen'
mailchimp-list: ''

# Authors
authors:
  michael:
    name: Michael
    display_name: Michael
    gravatar: 6dbdef0376ac4867c80ff2274d6e8fc3
    email: motethansen@gmail.com
    web: https://michael.motethansen.com
    twitter: https://twitter.com/motethansen
    description: "Creator of this blog."
  
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge